// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv-puOKuVUVPgpYRRMMleSSXNoxonyPQQ',
    appId: '1:137167792494:web:33db4999d19feb630f397f',
    messagingSenderId: '137167792494',
    projectId: 'godrive-1d117',
    authDomain: 'godrive-1d117.firebaseapp.com',
    storageBucket: 'godrive-1d117.appspot.com',
    measurementId: 'G-MZSV9TLTW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcusgcosHp0BVC_pPywUzo-Cx35VqE2-s',
    appId: '1:137167792494:android:6d86abb2fae34acd0f397f',
    messagingSenderId: '137167792494',
    projectId: 'godrive-1d117',
    storageBucket: 'godrive-1d117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASKWZ_T4daZ84UKsm3BK3p34hn-mA_oZ8',
    appId: '1:137167792494:ios:a16359566561d1440f397f',
    messagingSenderId: '137167792494',
    projectId: 'godrive-1d117',
    storageBucket: 'godrive-1d117.appspot.com',
    iosBundleId: 'com.example.godrive',
  );
}
